version: '3.1'

services:
  mongodb:    
    hostname: mongodb
   # ports:
     # - "27015:27017"
      #- "27017:27017"
    image: mongo:4.4.2
    environment:
      - MONGO_INITDB_DATABASE=solid
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./db:/data/db
    
    restart: always
  apiserver:
    build: ./invapis 
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    links:
      - mongodb  
  client:
    build: solidvueapp/
    network_mode: host
    ports:
      - "8080:8080"
    depends_on:
      - apiserver   

    
